-- ============================================
-- ESQUEMA DE BASE DE DATOS PARA SISTEMA DE TURNOS
-- Ejecutar este SQL en el editor de SQL de Supabase
-- ============================================

-- Tabla de configuración
CREATE TABLE IF NOT EXISTS configuracion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clave TEXT UNIQUE NOT NULL,
    valor TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de proveedores
CREATE TABLE IF NOT EXISTS proveedores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_empresa TEXT NOT NULL,
    nit TEXT UNIQUE NOT NULL,
    contacto TEXT NOT NULL,
    telefono TEXT NOT NULL,
    servicio TEXT NOT NULL,
    fecha_registro TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de turnos
CREATE TABLE IF NOT EXISTS turnos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero TEXT NOT NULL,
    proveedor_id BIGINT REFERENCES proveedores(id),
    nombre_empresa TEXT NOT NULL,
    nit TEXT NOT NULL,
    motivo TEXT,
    hora_solicitud TEXT NOT NULL,
    fecha_solicitud TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    hora_llamada TEXT,
    estado TEXT NOT NULL DEFAULT 'espera',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de historial de turnos
CREATE TABLE IF NOT EXISTS historial_turnos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turno_id BIGINT,
    numero TEXT NOT NULL,
    nombre_empresa TEXT NOT NULL,
    nit TEXT NOT NULL,
    motivo TEXT,
    hora_solicitud TEXT NOT NULL,
    hora_llamada TEXT,
    hora_finalizacion TEXT,
    estado TEXT NOT NULL,
    fecha TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insertar configuración inicial del contador
INSERT INTO configuracion (clave, valor) 
VALUES ('contador_turnos', '0')
ON CONFLICT (clave) DO NOTHING;

-- Habilitar Real-time para las tablas
ALTER TABLE turnos REPLICA IDENTITY FULL;
ALTER TABLE historial_turnos REPLICA IDENTITY FULL;
ALTER TABLE proveedores REPLICA IDENTITY FULL;

-- Crear publicación para Real-time
DROP PUBLICATION IF EXISTS supabase_realtime;
CREATE PUBLICATION supabase_realtime FOR TABLE turnos, historial_turnos, proveedores;

-- Índices para mejorar rendimiento
CREATE INDEX IF NOT EXISTS idx_turnos_estado ON turnos(estado);
CREATE INDEX IF NOT EXISTS idx_turnos_fecha_solicitud ON turnos(fecha_solicitud);
CREATE INDEX IF NOT EXISTS idx_historial_turnos_fecha ON historial_turnos(fecha);
CREATE INDEX IF NOT EXISTS idx_proveedores_nit ON proveedores(nit);
