-- ============================================
-- ESQUEMA DE BASE DE DATOS PARA SISTEMA DE TURNOS
-- NUEVO PROYECTO - Ejecutar este SQL en el editor de SQL de Supabase
-- ============================================

-- Tabla de configuración del sistema
CREATE TABLE IF NOT EXISTS configuracion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clave TEXT UNIQUE NOT NULL,
    valor TEXT NOT NULL,
    descripcion TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de proveedores/empresas
CREATE TABLE IF NOT EXISTS proveedores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_empresa TEXT NOT NULL,
    nit TEXT UNIQUE NOT NULL,
    contacto TEXT NOT NULL,
    telefono TEXT NOT NULL,
    email TEXT,
    servicio TEXT NOT NULL,
    activo BOOLEAN DEFAULT true,
    fecha_registro TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de turnos activos
CREATE TABLE IF NOT EXISTS turnos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero TEXT NOT NULL,
    proveedor_id BIGINT REFERENCES proveedores(id) ON DELETE SET NULL,
    nombre_empresa TEXT NOT NULL,
    nit TEXT NOT NULL,
    motivo TEXT,
    hora_solicitud TEXT NOT NULL,
    fecha_solicitud TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    hora_llamada TEXT,
    hora_finalizacion TEXT,
    estado TEXT NOT NULL DEFAULT 'espera' CHECK (estado IN ('espera', 'atendiendo', 'completado', 'cancelado', 'citado')),
    prioridad INTEGER DEFAULT 0,
    notas TEXT,
    destino TEXT,
    fecha_cita TIMESTAMP WITH TIME ZONE,
    num_factura TEXT,
    bultos INTEGER,
    peso TEXT,
    responsable TEXT,
    autorizado_salida BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de historial de turnos (para reportes y análisis)
CREATE TABLE IF NOT EXISTS historial_turnos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turno_id BIGINT,
    numero TEXT NOT NULL,
    nombre_empresa TEXT NOT NULL,
    nit TEXT NOT NULL,
    motivo TEXT,
    hora_solicitud TEXT NOT NULL,
    hora_llamada TEXT,
    hora_finalizacion TEXT,
    estado TEXT NOT NULL CHECK (estado IN ('completado', 'cancelado')),
    tiempo_espera_minutos INTEGER,
    tiempo_atencion_minutos INTEGER,
    destino TEXT,
    fecha_cita TIMESTAMP WITH TIME ZONE,
    num_factura TEXT,
    bultos INTEGER,
    peso TEXT,
    responsable TEXT,
    contacto TEXT,
    telefono TEXT,
    servicio TEXT,
    autorizado_salida BOOLEAN DEFAULT false,
    fecha TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de usuarios del sistema (opcional para futuro)
CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    nombre TEXT NOT NULL,
    rol TEXT NOT NULL DEFAULT 'operador' CHECK (rol IN ('admin', 'operador', 'visualizador')),
    activo BOOLEAN DEFAULT true,
    ultimo_acceso TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- DATOS INICIALES
-- ============================================

-- Insertar configuración inicial del contador
INSERT INTO configuracion (clave, valor, descripcion) 
VALUES 
    ('contador_turnos', '0', 'Contador global de turnos emitidos'),
    ('turno_prefijo', 'T', 'Prefijo para los números de turno'),
    ('tiempo_maximo_espera', '30', 'Tiempo máximo de espera en minutos antes de alerta')
ON CONFLICT (clave) DO NOTHING;

-- Insertar usuario administrador por defecto
INSERT INTO usuarios (email, nombre, rol)
VALUES ('admin@sistema.com', 'Administrador', 'admin')
ON CONFLICT (email) DO NOTHING;

-- ============================================
-- ÍNDICES PARA OPTIMIZACIÓN
-- ============================================

-- Índices para la tabla turnos
CREATE INDEX IF NOT EXISTS idx_turnos_estado ON turnos(estado);
CREATE INDEX IF NOT EXISTS idx_turnos_fecha_solicitud ON turnos(fecha_solicitud);
CREATE INDEX IF NOT EXISTS idx_turnos_nit ON turnos(nit);
CREATE INDEX IF NOT EXISTS idx_turnos_proveedor_id ON turnos(proveedor_id);
CREATE INDEX IF NOT EXISTS idx_turnos_numero ON turnos(numero);

-- Índices para la tabla historial_turnos
CREATE INDEX IF NOT EXISTS idx_historial_turnos_fecha ON historial_turnos(fecha);
CREATE INDEX IF NOT EXISTS idx_historial_turnos_nit ON historial_turnos(nit);
CREATE INDEX IF NOT EXISTS idx_historial_turnos_estado ON historial_turnos(estado);

-- Índices para la tabla proveedores
CREATE INDEX IF NOT EXISTS idx_proveedores_nit ON proveedores(nit);
CREATE INDEX IF NOT EXISTS idx_proveedores_nombre ON proveedores(nombre_empresa);
CREATE INDEX IF NOT EXISTS idx_proveedores_activo ON proveedores(activo);

-- Índices para la tabla usuarios
CREATE INDEX IF NOT EXISTS idx_usuarios_email ON usuarios(email);
CREATE INDEX IF NOT EXISTS idx_usuarios_rol ON usuarios(rol);

-- ============================================
-- FUNCIONES Y TRIGGERS
-- ============================================

-- Función para actualizar updated_at automáticamente
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Triggers para actualizar updated_at
CREATE TRIGGER update_configuracion_updated_at 
    BEFORE UPDATE ON configuracion 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_proveedores_updated_at 
    BEFORE UPDATE ON proveedores 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_turnos_updated_at 
    BEFORE UPDATE ON turnos 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_usuarios_updated_at 
    BEFORE UPDATE ON usuarios 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- CONFIGURACIÓN DE REAL-TIME
-- ============================================

-- Habilitar Real-time para las tablas principales
ALTER TABLE turnos REPLICA IDENTITY FULL;
ALTER TABLE historial_turnos REPLICA IDENTITY FULL;
ALTER TABLE proveedores REPLICA IDENTITY FULL;
ALTER TABLE configuracion REPLICA IDENTITY FULL;

-- Crear publicación para Real-time
DROP PUBLICATION IF EXISTS supabase_realtime;
CREATE PUBLICATION supabase_realtime FOR TABLE turnos, historial_turnos, proveedores, configuracion;

-- ============================================
-- POLÍTICAS DE SEGURIDAD (ROW LEVEL SECURITY)
-- ============================================

-- Habilitar RLS en las tablas
ALTER TABLE turnos ENABLE ROW LEVEL SECURITY;
ALTER TABLE historial_turnos ENABLE ROW LEVEL SECURITY;
ALTER TABLE proveedores ENABLE ROW LEVEL SECURITY;
ALTER TABLE configuracion ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;

-- Políticas para turnos (permitir todas las operaciones por ahora)
CREATE POLICY "Permitir todas las operaciones en turnos" ON turnos
    FOR ALL USING (true) WITH CHECK (true);

-- Políticas para historial_turnos
CREATE POLICY "Permitir todas las operaciones en historial_turnos" ON historial_turnos
    FOR ALL USING (true) WITH CHECK (true);

-- Políticas para proveedores
CREATE POLICY "Permitir todas las operaciones en proveedores" ON proveedores
    FOR ALL USING (true) WITH CHECK (true);

-- Políticas para configuracion
CREATE POLICY "Permitir todas las operaciones en configuracion" ON configuracion
    FOR ALL USING (true) WITH CHECK (true);

-- Políticas para usuarios
CREATE POLICY "Permitir todas las operaciones en usuarios" ON usuarios
    FOR ALL USING (true) WITH CHECK (true);

-- ============================================
-- COMENTARIOS EN LAS TABLAS
-- ============================================

COMMENT ON TABLE configuracion IS 'Tabla de configuración del sistema';
COMMENT ON TABLE proveedores IS 'Tabla de proveedores/empresas registradas';
COMMENT ON TABLE turnos IS 'Tabla de turnos activos en el sistema';
COMMENT ON TABLE historial_turnos IS 'Tabla de historial de turnos para reportes';
COMMENT ON TABLE usuarios IS 'Tabla de usuarios del sistema';

COMMENT ON COLUMN turnos.estado IS 'Estados: espera, atendiendo, completado, cancelado, citado';
COMMENT ON COLUMN turnos.prioridad IS 'Prioridad del turno (0=normal, 1=alta, 2=urgente)';
COMMENT ON COLUMN turnos.destino IS 'Destino: SI ENSAMBLES, SI PLÁSTICOS, AMBOS';
COMMENT ON COLUMN turnos.fecha_cita IS 'Fecha y hora de la cita programada';
COMMENT ON COLUMN usuarios.rol IS 'Roles: admin, operador, visualizador';
