-- Tabla de mensajes entre admin y despachador
create table mensajes (
    id bigint generated by default as identity primary key,
    remitente text not null check (remitente in ('admin', 'despachador')),
    mensaje text not null,
    created_at timestamp with time zone default now(),
    leido boolean default false
);

-- Índices para rendimiento
create index idx_mensajes_created_at on mensajes(created_at desc);
create index idx_mensajes_leido on mensajes(leido);

-- Tabla para notificaciones de salida pendiente
create table notificaciones_salida (
    id bigint generated by default as identity primary key,
    turno_id bigint references turnos(id),
    proveedor_nit text,
    nombre_empresa text,
    fecha_cita timestamp with time zone,
    tipo text check (tipo in ('salida_pendiente', 'salida_autorizada')),
    mensaje text,
    created_at timestamp with time zone default now(),
    leido boolean default false
);

create index idx_notificaciones_salida_leido on notificaciones_salida(leido);
create index idx_notificaciones_salida_created_at on notificaciones_salida(created_at desc);